# Generated by Django 4.0.4 on 2022-05-31 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='სახელი')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('starting_price', models.IntegerField(verbose_name='საწყისი ფასი')),
                ('preferred_price', models.IntegerField(verbose_name='სასურველი ფასი')),
                ('send_to_email', models.BooleanField()),
                ('time', models.DateTimeField(auto_now=True, verbose_name='დრო')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction.category', verbose_name='კატეგორია')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი')),
            ],
        ),
    ]
