# Generated by Django 4.0.4 on 2022-06-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0004_bid_time_alter_bid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='დრო'),
        ),
    ]
