# Generated by Django 4.0.4 on 2022-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0006_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
