# Generated by Django 4.0.4 on 2022-06-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0008_alter_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='დრო'),
        ),
    ]
