# Generated by Django 4.0.4 on 2022-06-26 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0009_alter_bid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 16, 59, 30, 12637)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='დრო'),
        ),
    ]
