# Generated by Django 4.0.4 on 2022-06-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0012_alter_product_sold_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
