# Generated by Django 4.0.4 on 2022-05-24 17:51

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_id',
            field=models.BigIntegerField(default=0, validators=[User.models.validate_length], verbose_name='პირადი ნომერი'),
        ),
    ]
